version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ipswich_retail
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=f9ZPLnItXfdLYrxGgNQqA4E2FRgSg5KD
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 ipswich_retail.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=docker-secret-key-change-in-production
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgresql://ipswich_retail_user:f9ZPLnItXfdLYrxGgNQqA4E2FRgSg5KD@dpg-d6fkueea2pns73824p3g-a/ipswich_retail
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
